# hero_image_urls.py

"""
Relative local file paths for hero images under images/heroes.
"""

hero_image_urls = {
    "Black Panther": "images/heroes/1_Black Panther.jpg",
    "Captain Marvel": "images/heroes/2_Captain Marvel.jpg",
    "Iron Man": "images/heroes/3_Iron_Man.jpg",
    "She-Hulk": "images/heroes/4_She_Hulk.jpg",
    "Spider-Man Peter": "images/heroes/5_Spider-Man_(Peter Parker).jpg",
    "Captain America": "images/heroes/6_Captain_America.jpg",
    "Ms. Marvel": "images/heroes/7_Ms_Marvel.jpg",
    "Thor": "images/heroes/8_Thor.jpg",
    "Black Widow": "images/heroes/9_Black_Widow.jpg",
    "Doctor Strange": "images/heroes/10_Doctor_Strange.jpg",
    "Hulk": "images/heroes/11_Hulk.jpg",
    "Hawkeye": "images/heroes/12_Hawkeye.jpg",
    "Spider-Woman": "images/heroes/13_Spider_Woman.jpg",
    "Ant-Man": "images/heroes/14_Ant_Man.jpg",
    "Wasp": "images/heroes/15_Wasp.jpg",
    "Quicksilver": "images/heroes/16_Quicksilver.jpg",
    "Scarlet Witch": "images/heroes/17_Scarlet_Witch.jpg",
    "Groot": "images/heroes/18_Groot.jpg",
    "Rocket": "images/heroes/19_Rocket.jpg",
    "Star-Lord": "images/heroes/20_Star_Lord.jpg",
    "Gamora": "images/heroes/21_Gamora.jpg",
    "Drax": "images/heroes/22_Drax.jpg",
    "Venom (Flash)": "images/heroes/23_Venom.jpg",
    "Adam Warlock": "images/heroes/24_Adam_Warlock.jpg",
    "Spectrum": "images/heroes/25_Spectrum.jpg",
    "Nebula": "images/heroes/26_Nebula.jpg",
    "War Machine": "images/heroes/27_War_Machine.jpg",
    "Valkyrie": "images/heroes/28_Valkyrie.jpg",
    "Vision": "images/heroes/29_Vision.jpg",
    "Ghost Spider": "images/heroes/30_Ghost_Spider.jpg",
    "Spider-Man (Miles)": "images/heroes/31_Spider_Man_Miles.jpg",
    "Nova": "images/heroes/32_Nova.jpg",
    "Ironheart": "images/heroes/33_Ironheart.jpg",
    "Spider-Ham": "images/heroes/34_Spider_Ham.jpg",
    "SP//dr": "images/heroes/35_SPdr.jpg",
    "Colossus": "images/heroes/36_Colossus.jpg",
    "Shadowcat": "images/heroes/37_Shadowcat.jpg",
    "Cyclops": "images/heroes/38_Cyclops.jpg",
    "Phoenix": "images/heroes/39_Phoenix.jpg",
    "Wolverine": "images/heroes/40_Wolverine.jpg",
    "Storm": "images/heroes/41_Storm.jpg",
    "Gambit": "images/heroes/42_Gambit.jpg",
    "Rogue": "images/heroes/43_Rogue.jpg",
    "Cable": "images/heroes/44_Cable.jpg",
    "Domino": "images/heroes/45_Domino.jpg",
    "Psylocke": "images/heroes/46_Psylocke.jpg",
    "Angel": "images/heroes/47_Angel.jpg",
    "X-23": "images/heroes/48_X_23.jpg",
    "Deadpool": "images/heroes/49_Deadpool.jpg",
    "Bishop": "images/heroes/50_Bishop.jpg",
    "Magik": "images/heroes/51_Magik.jpg",
    "Iceman": "images/heroes/52_Iceman.jpg",
    "Jubilee": "images/heroes/53_Jubilee.jpg",
    "Nightcrawler": "images/heroes/54_Nightcrawler.jpg",
    "Magneto": "images/heroes/55_Magneto.jpg",
    "Maria Hill": "images/heroes/56_Maria_Hill.jpg",
    "Nick Fury": "images/heroes/57_Nick_Fury.jpg",
    "Silk": "images/heroes/58_Silk.jpg",
    "Shuri": "images/heroes/59_Shuri.jpg",
    "Falcon": "images/heroes/60_Falcon.jpg",
    "Winter Soldier": "images/heroes/61_Winter_Soldier.jpg",
}
