# hero_image_urls = {
#     "Captain Marvel": "https://i.imgur.com/TJv0XwU.jpeg",
#     "Iron Man": "https://i.imgur.com/r0CCd9T.jpeg",
#     "Spider-Man Peter": "https://i.imgur.com/rUQCPiU.jpeg",
#     "Black Panther": "https://i.imgur.com/PbCKZF0.jpeg",
#     "She-Hulk": "https://i.imgur.com/XJyC93D.jpeg",
#     "Captain America": "https://i.imgur.com/pNCGX11.jpeg",
#     "Ms. Marvel": "https://i.imgur.com/6sA7dpm.jpeg",
#     "Thor": "https://i.imgur.com/9JV7MkM.jpeg",
#     "Black Widow": "https://i.imgur.com/Hk3mhos.jpeg",
#     "Doctor Strange": "https://i.imgur.com/oBsPO1l.jpeg",
#     "Hulk": "https://i.imgur.com/zC3FqPt.jpeg",
#     "Hawkeye": "https://i.imgur.com/pHG8eHM.jpeg",
#     "Spider-Woman": "https://i.imgur.com/XGFSCGB.jpeg",
#     "Ant-Man": "https://i.imgur.com/fRy4gYE.jpeg",
#     "Wasp": "https://i.imgur.com/qUpOKYD.jpeg",
#     "Quicksilver": "https://i.imgur.com/R6d5sXF.jpeg",
#     "Scarlet Witch": "https://i.imgur.com/PWRHJI5.jpeg",
#     "Groot": "https://i.imgur.com/b8jo7qL.jpeg",
#     "Rocket": "https://i.imgur.com/qzBttPC.jpeg",
#     "Star-Lord": "https://i.imgur.com/OqKpZvi.jpeg",
#     "Gamora": "https://i.imgur.com/4yKLqEK.jpeg",
#     "Drax": "https://i.imgur.com/HlC4xkL.jpeg",
#     "Venom (Flash)": "https://i.imgur.com/cs77kT6.jpeg",
#     "Spectrum": "https://i.imgur.com/7MD5bX7.jpeg",
#     "Adam Warlock": "https://i.imgur.com/jXqA4vR.jpeg",
#     "Nebula": "https://i.imgur.com/sDqKlRD.jpeg",
#     "War Machine": "https://i.imgur.com/DdwS6fC.jpeg",
#     "Valkyrie": "https://i.imgur.com/6PJpQic.jpeg",
#     "Vision": "https://i.imgur.com/EBfS6yg.jpeg",
#     "Ghost Spider": "https://i.imgur.com/2GEyrsW.jpeg",
#     "Spider-Man (Miles)": "https://i.imgur.com/QUXyFIH.jpeg",
#     "Nova": "https://i.imgur.com/IKXQlNM.jpeg",
#     "Ironheart": "https://i.imgur.com/5HhKJv5.jpeg",
#     "SP//dr": "https://i.imgur.com/hWf0S7s.jpeg",
#     "Spider-Ham": "https://i.imgur.com/bIigd7R.jpeg",
#     "Colossus": "https://i.imgur.com/E7GHo5B.jpeg",
#     "Cyclops": "https://i.imgur.com/KEifLjf.jpeg",
#     "Shadowcat": "https://i.imgur.com/gUDyBwx.jpeg",
#     "Phoenix": "https://i.imgur.com/egDlUEK.jpeg",
#     "Wolverine": "https://i.imgur.com/XBs6W2O.jpeg",
#     "Storm": "https://i.imgur.com/FHXnyBN.jpeg",
#     "Gambit": "https://i.imgur.com/t1fI34N.jpeg",
#     "Rogue": "https://i.imgur.com/eXtPWzs.jpeg",
#     "Cable": "https://i.imgur.com/JuTvG4a.jpeg",
#     "Domino": "https://i.imgur.com/AuGqACj.jpeg",
#     "Psylocke": "https://i.imgur.com/mvUX7es.jpeg",
#     "Angel": "https://i.imgur.com/vutfimf.jpeg",
#     "X-23": "https://i.imgur.com/XGrOdRt.jpeg",
#     "Deadpool": "https://i.imgur.com/VKttFit.jpeg",
#     "Bishop": "https://i.imgur.com/MFPhsfd.jpeg",
#     "Magik": "https://i.imgur.com/zvQvAWw.jpeg",
#     "Iceman": "https://i.imgur.com/Zz8fckB.jpeg",
#     "Jubilee": "https://i.imgur.com/i1I8kF8.jpeg",
#     "Nightcrawler": "https://i.imgur.com/5zk1bjK.jpeg",
#     "Magneto": "https://i.imgur.com/xN6Kfdv.jpeg",
#     "Maria Hill": "https://i.imgur.com/DpffPA9.jpeg",
#     "Nick Fury": "https://i.imgur.com/6STdIKk.jpeg",
#     "Shuri": "https://i.imgur.com/CdLOKBd.jpeg",
#     "Silk": "https://i.imgur.com/UCmYWV8.jpeg",
# }

hero_image_urls = {
    "Black Panther": "images/heroes/1_Black Panther.jpg",
    "Captain Marvel": "images/heroes/2_Captain Marvel.jpg",
    "Iron Man": "images/heroes/3_Iron_Man.jpg",
    "She-Hulk": "images/heroes/4_She_Hulk.jpg",
    "Spider-Man Peter": "images/heroes/5_Spider-Man_(Peter Parker).jpg",
    "Captain America": "images/heroes/6_Captain_America.jpg",
    "Ms. Marvel": "images/heroes/7_Ms_Marvel.jpg",
    "Thor": "images/heroes/8_Thor.jpg",
    "Black Widow": "images/heroes/9_Black_Widow.jpg",
    "Doctor Strange": "images/heroes/10_Doctor_Strange.jpg",
    "Hulk": "images/heroes/11_Hulk.jpg",
    "Hawkeye": "images/heroes/12_Hawkeye.jpg",
    "Spider-Woman": "images/heroes/13_Spider_Woman.jpg",
    "Ant-Man": "images/heroes/14_Ant_Man.jpg",
    "Wasp": "images/heroes/15_Wasp.jpg",
    "Quicksilver": "images/heroes/16_Quicksilver.jpg",
    "Scarlet Witch": "images/heroes/17_Scarlet_Witch.jpg",
    "Groot": "images/heroes/18_Groot.jpg",
    "Rocket": "images/heroes/19_Rocket.jpg",
    "Star-Lord": "images/heroes/20_Star_Lord.jpg",
    "Gamora": "images/heroes/21_Gamora.jpg",
    "Drax": "images/heroes/22_Drax.jpg",
    "Venom (Flash)": "images/heroes/23_Venom.jpg",
    "Adam Warlock": "images/heroes/24_Adam_Warlock.jpg",
    "Spectrum": "images/heroes/25_Spectrum.jpg",
    "Nebula": "images/heroes/26_Nebula.jpg",
    "War Machine": "images/heroes/27_War_Machine.jpg",
    "Valkyrie": "images/heroes/28_Valkyrie.jpg",
    "Vision": "images/heroes/29_Vision.jpg",
    "Ghost Spider": "images/heroes/30_Ghost_Spider.jpg",
    "Spider-Man (Miles)": "images/heroes/31_Spider_Man_Miles.jpg",
    "Nova": "images/heroes/32_Nova.jpg",
    "Ironheart": "images/heroes/33_Ironheart.jpg",
    "Spider-Ham": "images/heroes/34_Spider_Ham.jpg",
    "SP//dr": "images/heroes/35_SPdr.jpg",
    "Colossus": "images/heroes/36_Colossus.jpg",
    "Shadowcat": "images/heroes/37_Shadowcat.jpg",
    "Cyclops": "images/heroes/38_Cyclops.jpg",
    "Phoenix": "images/heroes/39_Phoenix.jpg",
    "Wolverine": "images/heroes/40_Wolverine.jpg",
    "Storm": "images/heroes/41_Storm.jpg",
    "Gambit": "images/heroes/42_Gambit.jpg",
    "Rogue": "images/heroes/43_Rogue.jpg",
    "Cable": "images/heroes/44_Cable.jpg",
    "Domino": "images/heroes/45_Domino.jpg",
    "Psylocke": "images/heroes/46_Psylocke.jpg",
    "Angel": "images/heroes/47_Angel.jpg",
    "X-23": "images/heroes/48_X_23.jpg",
    "Deadpool": "images/heroes/49_Deadpool.jpg",
    "Bishop": "images/heroes/50_Bishop.jpg",
    "Magik": "images/heroes/51_Magik.jpg",
    "Iceman": "images/heroes/52_Iceman.jpg",
    "Jubilee": "images/heroes/53_Jubilee.jpg",
    "Nightcrawler": "images/heroes/54_Nightcrawler.jpg",
    "Magneto": "images/heroes/55_Magneto.jpg",
    "Maria Hill": "images/heroes/56_Maria_Hill.jpg",
    "Nick Fury": "images/heroes/57_Nick_Fury.jpg",
}
