# villain_image_urls.py

"""
Relative local file paths for villain images in the Villains folder.
"""

villain_image_urls = {
    "Rhino": "Villains/1_Rhino_2.jpg",
    "Klaw": "Villains/2_klaw_2.jpg",
    "Ultron": "Villains/3_Ultron_2.jpg",
    "Risky Business": "Villains/4_Risky_Business_2.jpg",
    "Mutagen Formula": "Villains/5_Mutagen_Formula_2.jpg",
    "Wrecking Crew": "Villains/6_Wrecking_Crew_2.jpg",
    "Crossbones": "Villains/7_Crossbones_2.jpg",
    "Absorbing Man": "Villains/8_Absorbing_Man_2.jpg",
    "Taskmaster": "Villains/9_Taskmaster_2.jpg",
    "Zola": "Villains/10_Zola_2.jpg",
    "Red Skull": "Villains/11_Red_Skull_2.jpg",
    "Kang": "Villains/12_Kang_1.jpg",
    "Drang": "Villains/13_Drang_2.jpg",
    "Collector 1": "Villains/14_Collector_2.jpg",
    "Collector 2": "Villains/15_Collector_A1.jpg",
    "Nebula": "Villains/16_Nebula_2.jpg",
    "Ronan": "Villains/17_Ronan_2.jpg",
    "Ebony Maw": "Villains/18_Ebony_Maw_2.jpg",
    "Tower Defense": "Villains/19_Tower_Defense_2.jpg",
    "Thanos": "Villains/20_Thanos_2.jpg",
    "Hela": "Villains/21_Hela_2.jpg",
    "Loki": "Villains/22_Loki_2.jpg",
    "The Hood": "Villains/23_The_Hood_2.jpg",
    "Sandman": "Villains/24_Sandman_2.jpg",
    "Venom": "Villains/25_Venom_2.jpg",
    "Mysterio": "Villains/26_Mysterio_2.jpg",
    "Sinister Six": "Villains/27_Sinister_Six_2.jpg",
    "Venom Goblin": "Villains/28_Venom_Goblin_2.jpg",
    "Sabertooth": "Villains/29_Sabertooth_2.jpg",
    "Project Wideawake": "Villains/30_Project_Wideawake_2.jpg",
    "Master Mold": "Villains/31_Master_Mold_2.jpg",
    "Mansion Attack": "Villains/32_Mansion_Attack_2.jpg",
    "Magneto": "Villains/33_Magneto_2.jpg",
    "Magog": "Villains/34_Magog_A.jpg",
    "Spiral": "Villains/35_Spiral_2.jpg",
    "Mojo": "Villains/36_Mojo_2.jpg",
    "Morlock Siege": "Villains/37_Morlock_Siege_2.jpg",
    "On The Run": "Villains/38_On_The_Run_2.jpg",
    "Juggernaut": "Villains/39_Juggernaut_2.jpg",
    "Mister Sinister": "Villains/40_Mister_Sinister_2.jpg",
    "Stryfe": "Villains/41_Stryfe_2.jpg",
    "Unus": "Villains/42_Unus_2.jpg",
    "Four Horsemen": "Villains/43_Four_Horseman_2.jpg",
    "Apocalypse 1": "Villains/44_Apocalypse_1_2.jpg",
    "Dark Beast": "Villains/45_Dark_Beast_2.jpg",
    "Apocalypse 2": "Villains/46_Apocalypse_2_2.jpg",
    "Black Widow": "Villains/47_Black_Widow_2.jpg",
    "Batroc": "Villains/48_Batroc_2.jpg",
    "M.O.D.O.K.": "Villains/49_MODOK_2.jpg",
    "Thunderbolts": "Villains/50_Thunderbolts_2.jpg",
    "Baron Zemo": "Villains/51_Baron_Zemo_2.jpg",
}
