villain_strategies = {
    "Rhino": "Look out for his charge attacks. In solo be careful about going to alter-ego. Always keep track of how many advances are in the discard pile.",
    "Klaw": "Klaw adds a lot of pressure early. Minion control, tempo, and threat removal are key to defeating him.",
    "Ultron": "Ultron floods the board with drones. Make sure you can take them out. If your hero is bad at defeating multiple minions, add Hawkeye to your deck. If your hero deals with minions easy, still consider adding Hawkeye. Try to keep him on stage 1 of his main scheme. Building up your board while controlling minions is key to winning.",
    "Risky Business": "This is a bizzarre scenario. Don't flip Norman unless you can deal a big chunk of damage. Building your upgrades and supports while he is Norman Osborn is key to winning.",
    "Mutagen Formula": "There will be a lot of pressure early due to the encounter cards. His encounter deck isn't that scary, but he can flood the board with mid health minions. Stay in control of the minions, build your board, and try to one shot him on stage 3 if you can to avoid dealing with all the encounter cards.",
    "Wrecking Crew": "Prioritize taking out one villain at a time. Make heavy use of alter-ego since there is little presssure due to threat.",
    "Crossbones": "Crossbones has a lot of damage, but a generous main scheme. Playing heroes with good surviability will be helpful. His scariest card is Full Auto. Keep track of both copies, and make sure to keep your health high to avoid random losses.",
    "Absorbing Man": "Absorbing Man unforunately just doesn't do much. The Super Absorbing Power side scheme can give him a boost in power, so prioritize finishing that scheme when it's out. Absorbing Man is a good opportunity to try some of the heroes that are lower on the tier list.",
    "Taskmaster": "Taskmaster does a bit of everything, but nothing is that scary. Don't expect an easy game though! Rescuing the allies that have been Captured By Hydra will help a lot because they're very powerful!",
    "Zola": "Zola brings in a lot of tough minions and having Retaliate 1 is difficult to deal with. He doesn't have high health though. Take every opportunity you get to do big chunks of damage to him. Overkill ignores retaliate damage. Relentless Assault is a great card to add because it solves two problems at once (Minions and Retaliate). Do not underestimate Zola. The game can go bad in an instant!",
    "Red Skull": "Red Skull's ability to bring a side scheme into play every turn and increase his attack is very powerful. It's a lot to deal with. You can't let them pile up. Make sure to bring a Justice player to the table to help keep those schemes in line. Be prepared to deal with The Sleeper. You need to have a source of damage at the ready when The Sleeper comes into play.",
    "Kang": "Kang will throw many different challenges at the players. Particularly on stage 2 when he splits everyone up, you don't know what challenges you will face. Having a reliable hero that is self sufficient is key to surviving the second stage.",
    "Drang": "Drang pressures threat and uses the Badoon swarm. Solid thwarting and crowd control are useful.",
    "Collector 1": "Collector 1 adds your cards to the collection. Low ally and upgrade spam helps.",
    "Collector 2": "Collector 2 emphasizes escaping the museum. Focus on main scheme progress.",
    "Nebula": "Nebula charges up techniques. Interrupts and burst windows are strong against her.",
    "Ronan": "Ronan hits hard and fast with tough attachments. Stun-lock and tempo play are essential.",
    "Ebony Maw": "Maw’s spells have delayed effects. Planning and damage windows are key.",
    "Tower Defense": "Two villains and two towers. Split focus and coordinated threat removal help.",
    "Thanos": "Thanos shrugs off stun/confuse. Bring raw power and sustain.",
    "Hela": "Hela’s stages involve reviving minions. Momentum and targeted removal matter.",
    "Loki": "Loki swaps forms mid-fight. Adaptation and all-around coverage pay off.",
    "The Hood": "The Hood chains modulars. Expect surprises—build a flexible deck.",
    "Sandman": "Sandman scales threat and discards cards. Steady pacing and thwarting are important.",
    "Venom": "Venom has aggressive tempo. Efficient damage and heal mitigation are helpful.",
    "Mysterio": "Mysterio fills your deck with junk. Deck manipulation and resource filtering are strong.",
    "Sinister Six": "Multiple villains rotate. Focused damage and crowd control keep things stable.",
    "Venom Goblin": "Venom Goblin spreads threat across schemes. Efficient thwart and AOE are key.",
    "Sabertooth": "Sabertooth heals often. Burst damage and healing denial help you keep up.",
    "Project Wideawake": "Lots of Sentinels and capture mechanics. Prioritize freeing allies.",
    "Master Mold": "Master Mold produces sentinels quickly. Minion control is essential.",
    "Mansion Attack": "Team-based scenario with split threats. Coordination and area control work well.",
    "Magneto": "Magneto builds momentum with upgrades. Aggression and thwart balance are crucial.",
    "Magog": "Magog builds a stadium score. Deny points and pivot to burst damage.",
    "Spiral": "Spiral hides in side schemes. Thwart-heavy decks can find and defeat her quickly.",
    "Mojo": "Mojo’s changing shows alter the fight. Stay versatile and ready for surprises.",
    "Morlock Siege": "Rescue allies and control minions. Balanced stat lines shine here.",
    "On The Run": "A mobile villain that shifts zones. Mobility and quick scheme clears are helpful.",
    "Juggernaut": "Juggernaut hits hard and often. Defense and healing are crucial.",
    "Mister Sinister": "Sinister mutates minions and stats. Removal and control are valuable.",
    "Stryfe": "Stryfe mixes threat and force. Versatile decks and reactiveness are helpful.",
    "Unus": "Unus uses barriers and resistance. High-damage and piercing cards work best.",
    "Four Horsemen": "Multiple strong villains—balance is key. Adapt between damage and control.",
    "Apocalypse 1": "Stage one of a long battle. Build up carefully and conserve resources.",
    "Dark Beast": "Dark Beast uses science and sabotage. Denial and disruption shine here.",
    "Apocalypse 2": "Endgame boss mode. Bring your strongest builds and consistent answers.",
}
