villain_strategies = {
    "Rhino": "Look out for his charge attacks. In solo be careful about going to alter-ego. Always keep track of how many advances are in the discard pile.",
    "Klaw": "Klaw adds a lot of pressure early. Minion control, tempo, and threat removal are key to defeating him.",
    "Ultron": "Ultron floods the board with drones. Make sure you can take them out. If your hero is bad at defeating multiple minions, add Hawkeye to your deck. If your hero deals with minions easy, still consider adding Hawkeye. Try to keep him on stage 1 of his main scheme. Building up your board while controlling minions is key to winning.",
    "Risky Business": "This is a bizzarre scenario. Don't flip Norman unless you can deal a big chunk of damage. Building your upgrades and supports while he is Norman Osborn is key to winning.",
    "Mutagen Formula": "Expect early chaos with lots of minions. Quick removal and tempo control matter.",
    "Wrecking Crew": "Four villains at once! Managing multiple threats and prioritizing targets is essential.",
    "Crossbones": "Crossbones scales quickly with weapons. Control the tech and watch for nasty upgrades.",
    "Absorbing Man": "Track the environment and adapt. He’s reactive and conditionally dangerous.",
    "Taskmaster": "Taskmaster punishes identity flips. Timing your changes and rescuing allies is key.",
    "Zola": "Zola brings tough minions and tech. High burst damage and minion control help here.",
    "Red Skull": "Side schemes pile up fast. Balancing scheme control and damage is crucial.",
    "Kang": "Kang is a multi-stage fight with changing rules. Versatility and adaptability shine.",
    "Drang": "Drang pressures threat and uses the Badoon swarm. Solid thwarting and crowd control are useful.",
    "Collector 1": "Collector 1 adds your cards to the collection. Low ally and upgrade spam helps.",
    "Collector 2": "Collector 2 emphasizes escaping the museum. Focus on main scheme progress.",
    "Nebula": "Nebula charges up techniques. Interrupts and burst windows are strong against her.",
    "Ronan": "Ronan hits hard and fast with tough attachments. Stun-lock and tempo play are essential.",
    "Ebony Maw": "Maw’s spells have delayed effects. Planning and damage windows are key.",
    "Tower Defense": "Two villains and two towers. Split focus and coordinated threat removal help.",
    "Thanos": "Thanos shrugs off stun/confuse. Bring raw power and sustain.",
    "Hela": "Hela’s stages involve reviving minions. Momentum and targeted removal matter.",
    "Loki": "Loki swaps forms mid-fight. Adaptation and all-around coverage pay off.",
    "The Hood": "The Hood chains modulars. Expect surprises—build a flexible deck.",
    "Sandman": "Sandman scales threat and discards cards. Steady pacing and thwarting are important.",
    "Venom": "Venom has aggressive tempo. Efficient damage and heal mitigation are helpful.",
    "Mysterio": "Mysterio fills your deck with junk. Deck manipulation and resource filtering are strong.",
    "Sinister Six": "Multiple villains rotate. Focused damage and crowd control keep things stable.",
    "Venom Goblin": "Venom Goblin spreads threat across schemes. Efficient thwart and AOE are key.",
    "Sabertooth": "Sabertooth heals often. Burst damage and healing denial help you keep up.",
    "Project Wideawake": "Lots of Sentinels and capture mechanics. Prioritize freeing allies.",
    "Master Mold": "Master Mold produces sentinels quickly. Minion control is essential.",
    "Mansion Attack": "Team-based scenario with split threats. Coordination and area control work well.",
    "Magneto": "Magneto builds momentum with upgrades. Aggression and thwart balance are crucial.",
    "Magog": "Magog builds a stadium score. Deny points and pivot to burst damage.",
    "Spiral": "Spiral hides in side schemes. Thwart-heavy decks can find and defeat her quickly.",
    "Mojo": "Mojo’s changing shows alter the fight. Stay versatile and ready for surprises.",
    "Morlock Siege": "Rescue allies and control minions. Balanced stat lines shine here.",
    "On The Run": "A mobile villain that shifts zones. Mobility and quick scheme clears are helpful.",
    "Juggernaut": "Juggernaut hits hard and often. Defense and healing are crucial.",
    "Mister Sinister": "Sinister mutates minions and stats. Removal and control are valuable.",
    "Stryfe": "Stryfe mixes threat and force. Versatile decks and reactiveness are helpful.",
    "Unus": "Unus uses barriers and resistance. High-damage and piercing cards work best.",
    "Four Horsemen": "Multiple strong villains—balance is key. Adapt between damage and control.",
    "Apocalypse 1": "Stage one of a long battle. Build up carefully and conserve resources.",
    "Dark Beast": "Dark Beast uses science and sabotage. Denial and disruption shine here.",
    "Apocalypse 2": "Endgame boss mode. Bring your strongest builds and consistent answers.",
}
