# Villain image urls

villain_image_urls = {
    "Rhino": "https://i.imgur.com/g51Eseo.jpeg",
    "Klaw": "https://i.imgur.com/xT5uItU.jpeg",
    "Ultron": "https://i.imgur.com/RpXFGVK.jpeg",
    "Risky Business": "https://i.imgur.com/RjjNSrR.jpeg",
    "Mutagen Formula": "https://i.imgur.com/E9LJfJK.jpeg",
    "Wrecking Crew": "https://i.imgur.com/odJwudi.jpeg",
    "Crossbones": "https://i.imgur.com/Yh1nlna.jpeg",
    "Absorbing Man": "https://i.imgur.com/nefdKCJ.jpeg",
    "Taskmaster": "https://i.imgur.com/Q8yTJjF.jpeg",
    "Zola": "https://i.imgur.com/8Lw7gFK.jpeg",
    "Red Skull": "https://i.imgur.com/si4YArG.jpeg",
    "Kang": "https://i.imgur.com/u8EeB5R.jpeg",
    "Drang": "https://i.imgur.com/kHkHpf5.jpeg",
    "Collector 1": "https://i.imgur.com/vEySTbv.jpeg",
    "Collector 2": "https://i.imgur.com/lgbNLb6.jpeg",
    "Nebula": "https://i.imgur.com/yDQHm1M.jpeg",
    "Ronan": "https://i.imgur.com/uHy3Tit.jpeg",
    "Ebony Maw": "https://example.com/ebonymaw.jpeg",
    "Tower Defense": "https://example.com/towerdefense.jpeg",
    "Thanos": "https://example.com/thanos.jpeg",
    "Hela": "https://example.com/hela.jpeg",
    "Loki": "https://example.com/loki.jpeg",
    "The Hood": "https://example.com/thehood.jpeg",
    "Sandman": "https://example.com/sandman.jpeg",
    "Venom": "https://example.com/venom.jpeg",
    "Mysterio": "https://example.com/mysterio.jpeg",
    "Sinister Six": "https://example.com/sinistersix.jpeg",
    "Venom Goblin": "https://example.com/venomgoblin.jpeg",
    "Sabertooth": "https://example.com/sabertooth.jpeg",
    "Project Wideawake": "https://example.com/projectwideawake.jpeg",
    "Master Mold": "https://example.com/mastermold.jpeg",
    "Mansion Attack": "https://example.com/mansionattack.jpeg",
    "Magneto": "https://example.com/magneto.jpeg",
    "Magog": "https://example.com/magog.jpeg",
    "Spiral": "https://example.com/spiral.jpeg",
    "Mojo": "https://example.com/mojo.jpeg",
    "Morlock Siege": "https://example.com/morlocksiege.jpeg",
    "On The Run": "https://example.com/ontherun.jpeg",
    "Juggernaut": "https://example.com/juggernaut.jpeg",
    "Mister Sinister": "https://example.com/mistersinister.jpeg",
    "Stryfe": "https://example.com/stryfe.jpeg",
    "Unus": "https://example.com/unus.jpeg",
    "Four Horsemen": "https://example.com/fourhorsemen.jpeg",
    "Apocalypse 1": "https://example.com/apocalypse1.jpeg",
    "Dark Beast": "https://example.com/darkbeast.jpeg",
    "Apocalypse 2": "https://example.com/apocalypse2.jpeg",
}
