# Villain image urls

villain_image_urls = {
    "Rhino": "https://i.imgur.com/g51Eseo.jpeg",
    "Klaw": "https://i.imgur.com/xT5uItU.jpeg",
    "Ultron": "https://i.imgur.com/RpXFGVK.jpeg",
    "Risky Business": "https://i.imgur.com/RjjNSrR.jpeg",
    "Mutagen Formula": "https://i.imgur.com/E9LJfJK.jpeg",
    "Wrecking Crew": "https://i.imgur.com/odJwudi.jpeg",
    "Crossbones": "https://i.imgur.com/Yh1nlna.jpeg",
    "Absorbing Man": "https://i.imgur.com/nefdKCJ.jpeg",
    "Taskmaster": "https://i.imgur.com/Q8yTJjF.jpeg",
    "Zola": "https://i.imgur.com/8Lw7gFK.jpeg",
    "Red Skull": "https://i.imgur.com/si4YArG.jpeg",
    "Kang": "https://i.imgur.com/536AAJ0.jpeg",
    "Drang": "https://i.imgur.com/Ix5MWe1.jpeg",
    "Collector 1": "https://i.imgur.com/Wy1PSxd.jpeg",
    "Collector 2": "https://i.imgur.com/IrZCVgk.jpeg",
    "Nebula": "https://i.imgur.com/ps53aG2.jpeg",
    "Ronan": "https://i.imgur.com/U0VL9R3.jpeg",
    "Ebony Maw": "https://i.imgur.com/selZFWt.jpeg",
    "Tower Defense": "https://i.imgur.com/SHKgatn.jpeg",
    "Thanos": "https://i.imgur.com/jetUt8q.jpeg",
    "Hela": "https://i.imgur.com/3GSv4WT.jpeg",
    "Loki": "https://i.imgur.com/mfnDISa.jpeg",
    "The Hood": "https://i.imgur.com/EPuUGsl.jpeg",
    "Sandman": "https://i.imgur.com/55r9sDa.jpeg",
    "Venom": "https://i.imgur.com/HZYculf.jpeg",
    "Mysterio": "https://i.imgur.com/5qZYqAb.jpeg",
    "Sinister Six": "https://i.imgur.com/St1Icjv.jpeg",
    "Venom Goblin": "https://i.imgur.com/kPw7IXc.jpeg",
    "Sabertooth": "https://i.imgur.com/Fab1a9r.jpeg",
    "Project Wideawake": "https://i.imgur.com/qSXeaoE.jpeg",
    "Master Mold": "https://i.imgur.com/3tAYJBq.jpeg",
    "Mansion Attack": "https://i.imgur.com/Ds2kd7n.jpeg",
    "Magneto": "https://i.imgur.com/oE5hboY.jpeg",
    "Magog": "https://i.imgur.com/o7QhoAk.jpeg",
    "Spiral": "https://i.imgur.com/zD8pJjQ.jpeg",
    "Mojo": "https://i.imgur.com/WuVjuKy.jpeg",
    "Morlock Siege": "https://i.imgur.com/LEyGu1W.jpeg",
    "On The Run": "https://i.imgur.com/sgqkAVE.jpeg",
    "Juggernaut": "https://i.imgur.com/OndyFaZ.jpeg",
    "Mister Sinister": "https://i.imgur.com/GSeUBjs.jpeg",
    "Stryfe": "https://i.imgur.com/Z5UBBDu.jpeg",
    "Unus": "https://i.imgur.com/48cKj4k.jpeg",
    "Four Horsemen": "https://i.imgur.com/dMEsrf1.jpeg",
    "Apocalypse 1": "https://i.imgur.com/39XOEFs.jpeg",
    "Dark Beast": "https://i.imgur.com/JUpNfNG.jpeg",
    "Apocalypse 2": "https://i.imgur.com/kVJA1D1.jpeg",
}
